# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea8ab9a94a9fb7ac9bff53ae22a72825e13b938fcee926c3c605c5dd860e45ff568f4bc8f07740c376bb24c017ccdbdf414369ff7371b5ffbf60abc976de25a6

test:
  secret_key_base: 5014f0cde4fa592b51fb0057e5a043f42872a9b0b76757f0d7496cb3a05457262f85eac35fcbfe0ca4e444ad3cfa0701246b5303986de0849e73d04e727a3513

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
